### ISSUE TITLE
LWM2M.xsd: wrong type for Object ID and Resource ID

### ISSUE THREAD

**Issue by vogtdominik** [OpenMobileAlliance/OMA-LwM2M-Public-Review#22] opened 2015-02-12 13:35 UTC
LWM2M.xsd version:
   version - 1.0
   date    - 21 Nov 2013

According to the LWM2M specification (OMA-TS-LightweightM2M-V1_0-20141126-C), the Object ID and Resource ID is a 16-bit unsigned integer. But the LWM2M.xsd defines unsignedByte instead of unsignedShort (see line 89 and 162 in http://openmobilealliance.org/tech/profiles/LWM2M.xsd).

**Comment by boaks** [comment] 2015-07-16 07:08
Duplicate of https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/59 ?

**Closed** 2015-07-18 13:15 UTC
Labels: Discrepancies, SUP, TS
