### ISSUE TITLE
Wrong type for ObjectID and ID in LWM2M.xsd

### ISSUE THREAD

**Issue by MKremserBosch** [OpenMobileAlliance/OMA-LwM2M-Public-Review#59] opened 2015-07-10 07:13 UTC
The LWM2M.xsd under http://technical.openmobilealliance.org/tech/profiles/LWM2M.xsd defines the following types 

    <xs:element name="ObjectID" type="xs:unsignedByte"/>
    <xs:attribute name="ID" type="xs:unsignedByte" use="required"/>

In the OMA-TS-LightweightM2M-V1_0_20150513-D in chapter 6.2 Identifiers the IDs are specified as 16-bit unsigned integer. Also in the appendix D.1 the Object ID is defined as 16-bit Unsigned Integer.

Please correct this type mismatch between TS and xsd. In the xsd there should be the type xs:unsignedShort.

**Comment by jpradocueva** [comment] 2015-07-14 16:07
OMA Device Management Group has reviewed the issue and a Change Request (CR) will be prepared to fix the problem. Once this CR is agreed and incorporated in the specifications this issue will be updated.

**Comment by jpradocueva** [comment] 2015-07-14 16:08
Thanks for reporting this bug.

**Comment by boaks** [comment] 2015-07-16 07:08
Duplicate of https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/22 ?

**Comment by vogtdominik** [comment] 2015-07-16 07:33
Yes, it is a duplicate of #22 

There is another bug in the XSD:
In line 153 the data type 'Integer' is repeated. Instead it should be 'Objlnk' as this data type is defined in appendix C but missing in the XSD.

Can you include that in the change request or should I create a new issue?

**Comment by ThGarnier** [comment] 2015-07-17 13:24
This has been addressed in CR 2015-0042 (July 2015)  (To Be Closed)

**Closed** 2015-07-18 13:19 UTC
Labels: bug
